package math.StatisticsPackage;


/**
* math/StatisticsPackage/NumberSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Statistics.idl
* Montag, 4. April 2011 14:35 Uhr MESZ
*/

public final class NumberSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public double value[] = null;

  public NumberSeqHolder ()
  {
  }

  public NumberSeqHolder (double[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = math.StatisticsPackage.NumberSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    math.StatisticsPackage.NumberSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return math.StatisticsPackage.NumberSeqHelper.type ();
  }

}
