package math;

/**
* math/StatisticsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Statistics.idl
* Montag, 4. April 2011 14:35 Uhr MESZ
*/

public final class StatisticsHolder implements org.omg.CORBA.portable.Streamable
{
  public math.Statistics value = null;

  public StatisticsHolder ()
  {
  }

  public StatisticsHolder (math.Statistics initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = math.StatisticsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    math.StatisticsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return math.StatisticsHelper.type ();
  }

}
