package math;


/**
* math/Statistics.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Statistics.idl
* Montag, 4. April 2011 14:35 Uhr MESZ
*/

public interface Statistics extends StatisticsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Statistics
