package math;


/**
* math/StatisticsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Statistics.idl
* Montag, 4. April 2011 14:35 Uhr MESZ
*/

public interface StatisticsOperations 
{
  void setNumbers (double[] numbers);
  double getAverage ();
} // interface StatisticsOperations
